name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: git clone
        uses: actions/checkout@v2
      
      - name: Install Packages
        run: yarn install
      
      - name: Build
        run: yarn build
      
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_S3_ACCESS_KEY }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://devplutus-portfolio
